[2024-12-15T16:32:02.288+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tuyensinh_pipeline.crawl_notifications manual__2024-12-15T16:31:48.866692+00:00 [queued]>
[2024-12-15T16:32:02.297+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tuyensinh_pipeline.crawl_notifications manual__2024-12-15T16:31:48.866692+00:00 [queued]>
[2024-12-15T16:32:02.298+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-12-15T16:32:02.314+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): crawl_notifications> on 2024-12-15 16:31:48.866692+00:00
[2024-12-15T16:32:02.323+0000] {standard_task_runner.py:57} INFO - Started process 82 to run task
[2024-12-15T16:32:02.327+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'tuyensinh_pipeline', 'crawl_notifications', 'manual__2024-12-15T16:31:48.866692+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/tuyensinh_dag.py', '--cfg-path', '/tmp/tmpbmqrrcc6']
[2024-12-15T16:32:02.330+0000] {standard_task_runner.py:85} INFO - Job 23: Subtask crawl_notifications
[2024-12-15T16:32:02.394+0000] {task_command.py:415} INFO - Running <TaskInstance: tuyensinh_pipeline.crawl_notifications manual__2024-12-15T16:31:48.866692+00:00 [running]> on host c2e1e1d4ea8c
[2024-12-15T16:32:02.485+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NghiaLT' AIRFLOW_CTX_DAG_ID='tuyensinh_pipeline' AIRFLOW_CTX_TASK_ID='crawl_notifications' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T16:31:48.866692+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-15T16:31:48.866692+00:00'
[2024-12-15T16:32:02.489+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/common/driver_finder.py", line 64, in _binary_paths
    raise ValueError(f"The path is not a valid file: {path}")
ValueError: The path is not a valid file: /path/to/chromedriver

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/notification_pipeline.py", line 347, in crawl_notifications_task
    total_crawled = crawler.crawl_notifications(chrome_driver_path='/path/to/chromedriver')
  File "/opt/airflow/pipelines/notification_pipeline.py", line 142, in crawl_notifications
    driver = webdriver.Chrome(service=chrome_service, options=self.chrome_options)
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 50, in __init__
    if finder.get_browser_path():
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/common/driver_finder.py", line 47, in get_browser_path
    return self._binary_paths()["browser_path"]
  File "/home/airflow/.local/lib/python3.9/site-packages/selenium/webdriver/common/driver_finder.py", line 78, in _binary_paths
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2024-12-15T16:32:02.502+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=tuyensinh_pipeline, task_id=crawl_notifications, execution_date=20241215T163148, start_date=20241215T163202, end_date=20241215T163202
[2024-12-15T16:32:02.518+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 23 for task crawl_notifications (Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
; 82)
[2024-12-15T16:32:02.538+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-15T16:32:02.563+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
