[2024-12-15T10:39:44.748+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tuyensinh_pipeline.etl_to_mysql scheduled__2024-12-14T00:00:00+00:00 [queued]>
[2024-12-15T10:39:44.756+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tuyensinh_pipeline.etl_to_mysql scheduled__2024-12-14T00:00:00+00:00 [queued]>
[2024-12-15T10:39:44.757+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-12-15T10:39:44.772+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): etl_to_mysql> on 2024-12-14 00:00:00+00:00
[2024-12-15T10:39:44.777+0000] {standard_task_runner.py:57} INFO - Started process 79 to run task
[2024-12-15T10:39:44.780+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'tuyensinh_pipeline', 'etl_to_mysql', 'scheduled__2024-12-14T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/tuyensinh_dag.py', '--cfg-path', '/tmp/tmp32yo58d7']
[2024-12-15T10:39:44.782+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask etl_to_mysql
[2024-12-15T10:39:44.839+0000] {task_command.py:415} INFO - Running <TaskInstance: tuyensinh_pipeline.etl_to_mysql scheduled__2024-12-14T00:00:00+00:00 [running]> on host a4387a505c06
[2024-12-15T10:39:44.914+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NghiaLT' AIRFLOW_CTX_DAG_ID='tuyensinh_pipeline' AIRFLOW_CTX_TASK_ID='etl_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-14T00:00:00+00:00'
[2024-12-15T10:39:44.919+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/wish_pipeline.py", line 112, in etl_to_mysql
    sinh_vien = pd.read_csv('sinh_vien.csv', encoding='utf-8-sig')
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'sinh_vien.csv'
[2024-12-15T10:39:44.932+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=tuyensinh_pipeline, task_id=etl_to_mysql, execution_date=20241214T000000, start_date=20241215T103944, end_date=20241215T103944
[2024-12-15T10:39:44.947+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task etl_to_mysql ([Errno 2] No such file or directory: 'sinh_vien.csv'; 79)
[2024-12-15T10:39:44.992+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-15T10:39:45.007+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-15T12:23:19.129+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=tuyensinh_pipeline/run_id=scheduled__2024-12-14T00:00:00+00:00/task_id=etl_to_mysql permission to 509
[2024-12-15T12:23:19.136+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=tuyensinh_pipeline/run_id=scheduled__2024-12-14T00:00:00+00:00/task_id=etl_to_mysql permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=tuyensinh_pipeline/run_id=scheduled__2024-12-14T00:00:00+00:00/task_id=etl_to_mysql'
[2024-12-15T12:23:19.166+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=tuyensinh_pipeline/run_id=scheduled__2024-12-14T00:00:00+00:00/task_id=etl_to_mysql permission to 509
[2024-12-15T12:23:19.167+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=tuyensinh_pipeline/run_id=scheduled__2024-12-14T00:00:00+00:00/task_id=etl_to_mysql permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=tuyensinh_pipeline/run_id=scheduled__2024-12-14T00:00:00+00:00/task_id=etl_to_mysql'
[2024-12-15T12:23:19.191+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tuyensinh_pipeline.etl_to_mysql scheduled__2024-12-14T00:00:00+00:00 [queued]>
[2024-12-15T12:23:19.198+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tuyensinh_pipeline.etl_to_mysql scheduled__2024-12-14T00:00:00+00:00 [queued]>
[2024-12-15T12:23:19.199+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-12-15T12:23:19.213+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): etl_to_mysql> on 2024-12-14 00:00:00+00:00
[2024-12-15T12:23:19.221+0000] {standard_task_runner.py:57} INFO - Started process 79 to run task
[2024-12-15T12:23:19.225+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'tuyensinh_pipeline', 'etl_to_mysql', 'scheduled__2024-12-14T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/tuyensinh_dag.py', '--cfg-path', '/tmp/tmpeopviizj']
[2024-12-15T12:23:19.227+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask etl_to_mysql
[2024-12-15T12:23:19.277+0000] {logging_mixin.py:151} INFO - Changing /opt/airflow/logs/dag_id=tuyensinh_pipeline/run_id=scheduled__2024-12-14T00:00:00+00:00/task_id=etl_to_mysql permission to 509
[2024-12-15T12:23:19.278+0000] {logging_mixin.py:151} INFO - Failed to change /opt/airflow/logs/dag_id=tuyensinh_pipeline/run_id=scheduled__2024-12-14T00:00:00+00:00/task_id=etl_to_mysql permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=tuyensinh_pipeline/run_id=scheduled__2024-12-14T00:00:00+00:00/task_id=etl_to_mysql'
[2024-12-15T12:23:19.279+0000] {task_command.py:415} INFO - Running <TaskInstance: tuyensinh_pipeline.etl_to_mysql scheduled__2024-12-14T00:00:00+00:00 [running]> on host c3a2b43d39be
[2024-12-15T12:23:19.349+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NghiaLT' AIRFLOW_CTX_DAG_ID='tuyensinh_pipeline' AIRFLOW_CTX_TASK_ID='etl_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-14T00:00:00+00:00'
[2024-12-15T12:23:19.355+0000] {logging_mixin.py:151} INFO - Lỗi khi thực hiện ETL: 1044 (42000): Access denied for user 'airflow_user'@'%' to database 'university_data'
[2024-12-15T12:23:19.356+0000] {logging_mixin.py:151} INFO - Kết nối MySQL đã đóng
[2024-12-15T12:23:19.356+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-12-15T12:23:19.364+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=tuyensinh_pipeline, task_id=etl_to_mysql, execution_date=20241214T000000, start_date=20241215T122319, end_date=20241215T122319
[2024-12-15T12:23:19.396+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-12-15T12:23:19.411+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
